### ISSUE TITLE
Transfer: error is not caught when the mosaic format is wrong

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-cli#152]
1. Expected behavior and actual behavior.
Would expect a clean error when the mosaic format is wrong

2. Steps to reproduce the problem.
nem2-cli transaction transfer
address
1 nem.xem

3. Specifications like the version of the project, operating system, or hardware.
Ubuntu 16, node 12

Error:
Error: Invalid size for MosaicId hexadecimal notation
    at new MosaicId (/e/dev/nem2-cli/node_modules/nem2-sdk/dist/src/model/mosaic/MosaicId.js:53:23)
    at Function.getMosaicId (/e/dev/nem2-cli/build/src/service/mosaic.service.js:48:24)
    at /e/dev/nem2-cli/build/src/service/mosaic.service.js:57:53
    at Array.forEach (<anonymous>)
    at Function.getMosaics (/e/dev/nem2-cli/build/src/service/mosaic.service.js:55:21)
    at default_1.execute (/e/dev/nem2-cli/build/src/commands/transaction/transfer.js:104:54)
    at CLI.executeCommand (/e/dev/nem2-cli/node_modules/clime/bld/core/cli.js:225:24)
    at CLI.<anonymous> (/e/dev/nem2-cli/node_modules/clime/bld/core/cli.js:80:39)
    at Generator.next (<anonymous>)
    at fulfilled (/e/dev/nem2-cli/node_modules/clime/bld/core/cli.js:4:58)

**Comment by dgarcia360** [comment]
After reviewing the issue, custom validation in the whole CLI is currently taken into account when passing the value as a flag e.g. ``nem2-cli transaction transfer --mosaic-id <value>``, but not when entering the parameters interactively. 

As a potential solution, we might need to call each validators every time a new option is entered:

`` new MosaicIdAliasValidator().validate(mosaicId);``

**Comment by decentraliser** [comment]
yes, that's why I did so with the password!
