### ISSUE TITLE
Transaction information error after announcing lock funds tx

### ISSUE THREAD

**Issue by mijinc0** [nemtech/nem2-cli#8]
### 1. Expected behavior and actual behavior.

I can't see transaction infomation after announcing lock funds transaction.

### 2. Steps to reproduce the problem.

**before announcing lock funds transaciton**

```
~$ nem2-cli transaction transfer --recipient SBFAEPBIT3AY5B6JKWDJI27WGUY6IRKEBC6QSXBD --message "payout of 10 xem" --mosaics nem:xem::10000000
Transaction announced correctly
Hash:    7A7CF65F6400C7D3512FA44EBBD176AE39408EE137C0BBBA90DA78EE4E5F6358
Signer:  2CD3F6E62443FA80B332D21F47D25F624EC172B32F8EA2B0650AF3E8F2361A26

~$ nem2-cli account outgoing --publickey 2CD3F6E62443FA80B332D21F47D25F624EC172B32F8EA2B0650AF3E8F2361A26
TransferTransaction: Recipient:SBFAEP-BIT3AY-5B6JKW-DJI27W-GUY6IR-KEBC6Q-SXBD Message:"payout of 10 xem" Mosaics: d525ad41d95fcf29:10000000 Signer:SAVCMW-PXDA6Q-GMHILX-XTAOSX-IM7P7L-ZJFIID-YFI3 Deadline:2018-07-03 Hash:7A7CF65F6400C7D3512FA44EBBD176AE39408EE137C0BBBA90DA78EE4E5F6358
```

 I can see outgoing transactions.

**after announcing lock funds transaction**

```
~$ nem2-cli transaction pullfunds --recipient SBFAEPBIT3AY5B6JKWDJI27WGUY6IRKEBC6QSXBD --message "invoice 10 xem" --mosaic nem:xem::10000000
connection open
Announce lock funds transaction
Hash:    0C346DF5BA20B41433D100C4037E3D77AA38B2685C24F7FBAB982C19394E78BA
Signer:  2CD3F6E62443FA80B332D21F47D25F624EC172B32F8EA2B0650AF3E8F2361A26 

Waiting for confirmation to announce pull funds transaction
```

(wait without doing anything)

```
~$ nem2-cli account outgoing --publickey 2CD3F6E62443FA80B332D21F47D25F624EC172B32F8EA2B0650AF3E8F2361A26
Error Error: fully qualified id is invalid due to empty part (:-3087871471161192663)
    at throwInvalidFqn (/usr/lib/node_modules/nem2-cli/node_modules/nem2-library/dist/coders/idGenerator.js:38:8)
    at findMosaicSeparatorIndex (/usr/lib/node_modules/nem2-cli/node_modules/nem2-library/dist/coders/idGenerator.js:45:34)
    at Object.generateMosaicId (/usr/lib/node_modules/nem2-cli/node_modules/nem2-library/dist/coders/idGenerator.js:87:30)
    at Object.mosaicId (/usr/lib/node_modules/nem2-cli/node_modules/nem2-library/dist/transactions/NamespaceMosaicId.js:18:32)
    at new MosaicId (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/model/mosaic/MosaicId.js:41:50)
    at CreateStandaloneTransactionFromDTO (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/transaction/CreateTransactionFromDTO.js:97:249)
    at Object.exports.CreateTransactionFromDTO (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/transaction/CreateTransactionFromDTO.js:66:16)
    at transactionsDTO.map (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/AccountHttp.js:147:51)
    at Array.map (<anonymous>)
    at MapSubscriber.Observable_1.Observable.fromPromise.map [as project] (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/AccountHttp.js:146:36)
```

 After announce lock funds transaction,I can't see outgoing transactions.
 And transaction info command too.
  
```
~$ nem2-cli transaction info --hash 0C346DF5BA20B41433D100C4037E3D77AA38B2685C24F7FBAB982C19394E78BA
Error Error: fully qualified id is invalid due to empty part (:-3087871471161192663)
    at throwInvalidFqn (/usr/lib/node_modules/nem2-cli/node_modules/nem2-library/dist/coders/idGenerator.js:38:8)
    at findMosaicSeparatorIndex (/usr/lib/node_modules/nem2-cli/node_modules/nem2-library/dist/coders/idGenerator.js:45:34)
    at Object.generateMosaicId (/usr/lib/node_modules/nem2-cli/node_modules/nem2-library/dist/coders/idGenerator.js:87:30)
    at Object.mosaicId (/usr/lib/node_modules/nem2-cli/node_modules/nem2-library/dist/transactions/NamespaceMosaicId.js:18:32)
    at new MosaicId (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/model/mosaic/MosaicId.js:41:50)
    at CreateStandaloneTransactionFromDTO (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/transaction/CreateTransactionFromDTO.js:97:249)
    at Object.exports.CreateTransactionFromDTO (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/transaction/CreateTransactionFromDTO.js:66:16)
    at MapSubscriber.Observable_1.Observable.fromPromise.map [as project] (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/TransactionHttp.js:55:47)
    at MapSubscriber._next (/usr/lib/node_modules/nem2-cli/node_modules/rxjs/operators/map.js:79:35)
    at MapSubscriber.Subscriber.next (/usr/lib/node_modules/nem2-cli/node_modules/rxjs/Subscriber.js:93:18)
```

 
 
###  3. Specifications like the version of the project, operating system, or hardware.

```
 ~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

```
~$ npm -v
6.1.0
~$ node -v
v9.11.1
```
I installed nem2-cli via npm on 7/2.

**Comment by jorisadri** [comment]
Did you installed the nem2-cli on the 7 February or the 2 July. 
Whats the version you are using?: `npm show nem2-cli version`
If you did this on the catapult-service-bootstrap there was a error with lock transactions this is solved in the updated catapult-service-bootstrap.

**Comment by dgarcia360** [comment]
Closed due to lack of activity. Seems it is fixed.
